-- ========================================================
-- CafeOps — 100 Cafe & Food Products Seed File
-- Database: PostgreSQL
-- All products are cafe/food/beverage items
-- ========================================================


INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Espresso Single Shot', 'CAF101', 'Rich single-origin espresso. Intense aroma, velvety crema.', 40, 280, 250, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '7 days', 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF101');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Espresso Double Shot', 'CAF102', 'Double espresso for espresso lovers. Extra bold and rich.', 80, 350, 300, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '7 days', 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF102');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Americano', 'CAF103', 'Espresso diluted with hot water. Bold, smooth, and clean finish.', 45, 320, 280, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '6 days', 'https://images.unsplash.com/photo-1551030173-122aabc4489c?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF103');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cappuccino', 'CAF104', 'Equal parts espresso, steamed milk, and thick milk foam. Classic Italian.', 55, 380, 340, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '5 days', 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF104');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Latte', 'CAF105', 'Espresso with velvety steamed milk. Mild, creamy, and comforting.', 60, 420, 380, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '4 days', 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF105');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Flat White', 'CAF106', 'Ristretto shots with micro-foamed whole milk. Stronger than a latte.', 55, 400, 360, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '3 days', 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF106');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Mocha', 'CAF107', 'Espresso with chocolate syrup and steamed milk. Rich and indulgent.', 65, 450, 410, 'CafeOps', 150, 1, 1, NOW() - INTERVAL '2 days', 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF107');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Latte', 'CAF108', 'Cold espresso poured over ice with chilled milk. Refreshing and bold.', 60, 430, 390, 'CafeOps', 120, 1, 2, NOW() - INTERVAL '7 days', 'https://images.unsplash.com/photo-1517959105821-eaf2591984d2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF108');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cold Brew', 'CAF109', '18-hour slow-steeped cold brew. Smooth, less acidic, naturally sweet.', 50, 400, 360, 'CafeOps', 150, 1, 2, NOW() - INTERVAL '6 days', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF109');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Frappuccino', 'CAF110', 'Blended espresso with ice, milk, and flavored syrup. Topped with cream.', 75, 520, 470, 'CafeOps', 100, 1, 2, NOW() - INTERVAL '4 days', 'https://images.unsplash.com/photo-1572490122747-3e92a2547abb?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF110');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Matcha Latte', 'CAF111', 'Ceremonial grade matcha whisked with steamed oat milk. Earthy and creamy.', 65, 450, 410, 'CafeOps', 100, 1, 3, NOW() - INTERVAL '7 days', 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF111');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chai Latte', 'CAF112', 'Spiced masala chai concentrate with steamed whole milk. Warm and aromatic.', 55, 390, 350, 'CafeOps', 120, 1, 3, NOW() - INTERVAL '6 days', 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF112');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Earl Grey Tea', 'CAF113', 'Premium bergamot-infused black tea. Served with lemon or milk.', 30, 250, 220, 'CafeOps', 150, 1, 3, NOW() - INTERVAL '5 days', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF113');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Green Tea', 'CAF114', 'Fresh brewed organic green tea. Light, refreshing, antioxidant-rich.', 25, 220, 180, 'CafeOps', 150, 1, 3, NOW() - INTERVAL '4 days', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF114');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Butter Croissant', 'CAF115', 'Flaky, golden French-style butter croissant. Baked fresh daily.', 80, 320, 290, 'CafeOps', 60, 1, 4, NOW() - INTERVAL '2 days', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF115');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chocolate Croissant', 'CAF116', 'Flaky croissant filled with dark chocolate bars. A classic French treat.', 90, 360, 320, 'CafeOps', 50, 1, 4, NOW() - INTERVAL '2 days', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF116');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Blueberry Muffin', 'CAF117', 'Moist vanilla muffin bursting with fresh blueberries. Sugar-topped.', 90, 350, 320, 'CafeOps', 50, 1, 4, NOW() - INTERVAL '1 day', 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF117');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Banana Bread', 'CAF118', 'Dense, moist banana loaf with walnut chunks. No refined sugar added.', 85, 340, 310, 'CafeOps', 40, 1, 4, NOW() - INTERVAL '1 day', 'https://images.unsplash.com/photo-1587380420429-a4ef6a0e86e2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF118');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Mango Smoothie', 'CAF119', 'Alphonso mango blended with yogurt and honey. Thick and tropical.', 80, 480, 440, 'CafeOps', 80, 1, 5, NOW() - INTERVAL '4 days', 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF119');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Berry Blast Smoothie', 'CAF120', 'Blueberry, strawberry, and raspberry blend with almond milk.', 85, 500, 460, 'CafeOps', 75, 1, 5, NOW() - INTERVAL '3 days', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF120');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Affogato', 'CAF121', 'Vanilla gelato drowned in a hot ristretto shot. An Italian classic.', 90, 480, 440, 'CafeOps', 50, 1, 6, NOW() - INTERVAL '3 days', 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF121');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Dirty Chai', 'CAF122', 'Masala chai with a double shot of espresso. Spicy, bold, and energising.', 70, 450, 410, 'CafeOps', 60, 1, 6, NOW() - INTERVAL '2 days', 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF122');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Dalgona Coffee', 'CAF123', 'Whipped instant coffee cloud over iced milk. Sweet, frothy, and creamy.', 65, 440, 400, 'CafeOps', 55, 1, 6, NOW() - INTERVAL '1 day', 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF123');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Rose Latte', 'CAF124', 'Rose water and espresso with steamed milk. Delicate floral sweetness.', 70, 450, 410, 'CafeOps', 50, 1, 6, NOW(), 'https://images.unsplash.com/photo-1485808191679-5f86510bd652?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF124');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Tiramisu Cup', 'CAF125', 'Classic Italian tiramisu with layers of espresso-soaked ladyfingers and mascarpone.', 130, 480, 430, 'CafeOps', 40, 1, 9, NOW() - INTERVAL '2 days', 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF125');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chocolate Lava Cake', 'CAF126', 'Warm chocolate cake with molten center. Served with ice cream.', 150, 520, 470, 'CafeOps', 30, 1, 9, NOW(), 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF126');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cheesecake Slice', 'CAF127', 'Creamy New York style cheesecake with graham cracker crust.', 140, 500, 450, 'CafeOps', 35, 1, 9, NOW(), 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF127');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Panna Cotta', 'CAF128', 'Silky Italian custard with fresh berries and berry coulis.', 125, 460, 410, 'CafeOps', 40, 1, 9, NOW(), 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF128');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chocolate Brownie', 'CAF129', 'Fudgy dark chocolate brownie with sea salt flakes.', 95, 380, 350, 'CafeOps', 40, 1, 9, NOW(), 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF129');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cinnamon Roll', 'CAF130', 'Soft brioche roll with cinnamon sugar and cream cheese glaze.', 100, 420, 380, 'CafeOps', 25, 1, 9, NOW(), 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF130');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Americano', 'CAF131', 'Chilled espresso over ice with cold water. Clean and crisp.', 45, 330, 300, 'CafeOps', 120, 1, 2, NOW(), 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF131');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Cappuccino', 'CAF132', 'Iced espresso with cold milk and foam. Italian summer style.', 60, 400, 360, 'CafeOps', 120, 1, 2, NOW(), 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF132');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Vietnamese Iced Coffee', 'CAF133', 'Strong dark roast coffee with sweetened condensed milk over ice.', 55, 420, 380, 'CafeOps', 100, 1, 2, NOW(), 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF133');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Mocha', 'CAF134', 'Cold espresso, chocolate, milk, and ice. Dessert in a cup.', 70, 480, 440, 'CafeOps', 100, 1, 2, NOW(), 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF134');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Flat White', 'CAF135', 'Cold micro-foamed milk with ristretto shots over ice.', 65, 450, 410, 'CafeOps', 100, 1, 2, NOW(), 'https://images.unsplash.com/photo-1517959105821-eaf2591984d2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF135');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Macchiato', 'CAF136', 'Espresso "stained" with a dash of foamed milk. Bold and quick.', 45, 310, 280, 'CafeOps', 150, 1, 1, NOW(), 'https://images.unsplash.com/photo-1485808191679-5f86510bd652?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF136');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cortado', 'CAF137', 'Equal parts espresso and warm milk. Less foam, maximum flavor.', 50, 350, 320, 'CafeOps', 150, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF137');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Oolong Tea', 'CAF138', 'Traditional semi-fermented Chinese tea. Floral and complex.', 30, 260, 210, 'CafeOps', 140, 1, 3, NOW(), 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF138');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Lavender Latte', 'CAF139', 'House-made lavender syrup with espresso and steamed oat milk.', 70, 460, 420, 'CafeOps', 90, 1, 3, NOW(), 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF139');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chamomile Honey Tea', 'CAF140', 'Soothing chamomile with raw local honey. Perfect for relaxation.', 35, 280, 240, 'CafeOps', 120, 1, 3, NOW(), 'https://images.unsplash.com/photo-1508615039623-a25605d2938d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF140');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Green Detox Smoothie', 'CAF141', 'Spinach, cucumber, green apple, ginger, and lemon. Energising.', 75, 460, 420, 'CafeOps', 70, 1, 5, NOW(), 'https://images.unsplash.com/photo-1610970880026-7e4e3cd2e9e6?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF141');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Strawberry Banana Smoothie', 'CAF142', 'Fresh strawberries and banana with oat milk and vanilla.', 80, 470, 430, 'CafeOps', 75, 1, 5, NOW(), 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF142');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Protein Power Smoothie', 'CAF143', 'Banana, peanut butter, Greek yogurt, and almond milk.', 90, 500, 460, 'CafeOps', 60, 1, 5, NOW(), 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF143');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Tropical Pineapple Smoothie', 'CAF144', 'Fresh pineapple with coconut milk and mango. Vacation in glass.', 85, 480, 440, 'CafeOps', 70, 1, 5, NOW(), 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF144');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Acai Bowl', 'CAF145', 'Acai berries with banana, granola, and coconut. Topped with berries.', 100, 520, 480, 'CafeOps', 50, 1, 5, NOW(), 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF145');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Pistachio Latte', 'CAF146', 'Espresso with pistachio cream and milk. Nutty and sophisticated.', 80, 480, 440, 'CafeOps', 50, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF146');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Turmeric Latte', 'CAF147', 'Turmeric with warm milk, honey, and spices. Anti-inflammatory.', 60, 400, 360, 'CafeOps', 70, 1, 6, NOW(), 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF147');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Honey Cinnamon Latte', 'CAF148', 'Espresso with cinnamon, honey, and warm milk. Cozy.', 65, 420, 380, 'CafeOps', 70, 1, 6, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF148');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Nitro Cold Brew', 'CAF149', 'Cold brew infused with nitrogen. Smooth, velvety, perfect crema.', 65, 450, 410, 'CafeOps', 60, 1, 2, NOW(), 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF149');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cardamom Latte', 'CAF150', 'Fragrant cardamom pods with espresso and steamed milk.', 70, 450, 410, 'CafeOps', 65, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF150');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Egg Coffee', 'CAF151', 'Dense espresso with whipped egg yolk and condensed milk.', 75, 460, 420, 'CafeOps', 50, 1, 6, NOW(), 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF151');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Almond Croissant', 'CAF152', 'Buttery croissant with almond cream and sliced almonds.', 100, 380, 340, 'CafeOps', 45, 1, 4, NOW(), 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF152');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cheese Danish', 'CAF153', 'Danish pastry with creamy cheese filling and fruit.', 85, 350, 310, 'CafeOps', 45, 1, 4, NOW(), 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF153');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Apple Pie Slice', 'CAF154', 'Fresh apple pie with caramelized apples. Served warm.', 110, 400, 360, 'CafeOps', 35, 1, 9, NOW(), 'https://images.unsplash.com/photo-1568571933382-74d440642117?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF154');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Carrot Cake', 'CAF155', 'Moist carrot cake with cream cheese frosting.', 95, 380, 340, 'CafeOps', 40, 1, 9, NOW(), 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF155');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Scone with Jam', 'CAF156', 'Freshly baked scone with clotted cream and jam.', 70, 320, 280, 'CafeOps', 55, 1, 4, NOW(), 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF156');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Glazed Donut', 'CAF157', 'Classic glazed donut. Soft, fluffy, perfectly sweet.', 40, 220, 180, 'CafeOps', 60, 1, 9, NOW(), 'https://images.unsplash.com/photo-1585337007292-cd4efb3470b2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF157');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chocolate Donut', 'CAF158', 'Chocolate covered donut with chocolate sprinkles.', 45, 240, 200, 'CafeOps', 55, 1, 9, NOW(), 'https://images.unsplash.com/photo-1585337007292-cd4efb3470b2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF158');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Strawberry Shortcake', 'CAF159', 'Fluffy sponge cake with fresh strawberries and whipped cream.', 120, 420, 380, 'CafeOps', 25, 1, 9, NOW(), 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF159');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Peppermint Tea', 'CAF160', 'Fresh peppermint leaves. Cooling and digestive.', 25, 220, 180, 'CafeOps', 140, 1, 3, NOW(), 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF160');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Chai Latte', 'CAF161', 'Cold spiced chai with ice and milk. Aromatic.', 60, 400, 360, 'CafeOps', 100, 1, 3, NOW(), 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF161');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Ginger Lemon Tea', 'CAF162', 'Fresh ginger with lemon and raw honey. Immune boosting.', 40, 300, 260, 'CafeOps', 130, 1, 3, NOW(), 'https://images.unsplash.com/photo-1508615039623-a25605d2938d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF162');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Black Tea', 'CAF163', 'Full-bodied Assam black tea. Rich and robust.', 28, 240, 200, 'CafeOps', 150, 1, 3, NOW(), 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF163');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Green Tea', 'CAF164', 'Cold brewed organic green tea. Refreshing.', 30, 280, 240, 'CafeOps', 130, 1, 2, NOW(), 'https://images.unsplash.com/photo-1517959105821-eaf2591984d2?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF164');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Rose Tea', 'CAF165', 'Dried rose petals brewed with black tea. Delicate floral.', 35, 300, 260, 'CafeOps', 110, 1, 3, NOW(), 'https://images.unsplash.com/photo-1508615039623-a25605d2938d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF165');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Iced Matcha', 'CAF166', 'Matcha over ice with cold oat milk. Vibrant green, fresh.', 65, 440, 400, 'CafeOps', 110, 1, 3, NOW(), 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF166');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Butterfly Pea Tea', 'CAF167', 'Vibrant blue floral tea. Changes color with lemon.', 45, 350, 300, 'CafeOps', 100, 1, 3, NOW(), 'https://images.unsplash.com/photo-1508615039623-a25605d2938d?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF167');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Mango Lassi', 'CAF168', 'Mango puree blended with yogurt and cardamom.', 75, 420, 380, 'CafeOps', 70, 1, 5, NOW(), 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF168');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Watermelon Refresher', 'CAF169', 'Fresh watermelon with lime and mint. Perfect cooler.', 70, 420, 380, 'CafeOps', 80, 1, 5, NOW(), 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF169');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Avocado Green Tea', 'CAF170', 'Creamy avocado with green tea and almond milk.', 95, 500, 460, 'CafeOps', 60, 1, 5, NOW(), 'https://images.unsplash.com/photo-1610970880026-7e4e3cd2e9e6?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF170');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Beet Latte', 'CAF171', 'Earthy beet powder with espresso and oat milk.', 75, 460, 420, 'CafeOps', 55, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF171');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Red Eye Coffee', 'CAF172', 'Filter coffee with double shot espresso. Maximum caffeine.', 50, 380, 340, 'CafeOps', 100, 1, 1, NOW(), 'https://images.unsplash.com/photo-1495474472456-4d71bcdd2085?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF172');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Maple Pecan Latte', 'CAF173', 'Pure maple syrup with toasted pecan cream.', 85, 480, 440, 'CafeOps', 50, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF173');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Date Milk Latte', 'CAF174', 'Creamy date paste with espresso and almond milk.', 80, 470, 430, 'CafeOps', 55, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF174');
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Sesame Latte', 'CAF175', 'Toasted sesame with espresso and milk. Nutty.', 75, 460, 420, 'CafeOps', 60, 1, 1, NOW(), 'https://images.unsplash.com/photo-1561882468-9110d70b3dda?w=600&auto=format&fit=crop&q=80' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = 'CAF175');

-- ========================================================
-- End of Cafe & Food Products (100 items total)
-- All 100 products are cafe/food/beverage items
-- ========================================================

