-- ========================================================
-- Generated SQL Script: Seeding 100 Realistic Retail Products
-- Database: PostgreSQL
-- ========================================================

INSERT INTO categories (name, store_id) SELECT 'Men''s Clothing', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Women''s Clothing', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Footwear', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Footwear' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Home & Kitchen', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Personal Care', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Personal Care' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Bags & Accessories', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Kids & Baby', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Kids & Baby' AND store_id = 1);
INSERT INTO categories (name, store_id) SELECT 'Stationery & Office', 1 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Stationery & Office' AND store_id = 1);

-- --------------------------------------------------------
-- Category: Men's Clothing
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Classic Denim Shirt', '30001', 'Rugged cotton denim shirt', 450.00, 1599.00, 1399.00, 'Levi''s', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30001');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30001'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30001') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30001') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Slim Fit Chinos', '30002', 'Comfortable stretch cotton chinos', 550.00, 1999.00, 1799.00, 'Dockers', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30002');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30002'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30002') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30002') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Crewneck Cotton Tee', '30003', 'Standard fit soft cotton tee', 120.00, 499.00, 399.00, 'Jockey', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30003');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30003'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30003') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30003') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Hooded Sweatshirt', '30004', 'Warm pullover fleece hoodie', 600.00, 2499.00, 1999.00, 'Puma', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30004');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30004'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30004') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30004') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Leather Biker Jacket', '30005', 'Premium faux leather jacket', 1500.00, 5999.00, 4999.00, 'Zara', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30005');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30005'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30005') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30005') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Linen Casual Trousers', '30006', 'Breathable linen blend trousers', 400.00, 1699.00, 1499.00, 'Marks & Spencer', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30006');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30006'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30006') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30006') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Striped Polo Shirt', '30007', 'Classic polo with horizontal stripes', 300.00, 1199.00, 999.00, 'Ralph Lauren', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30007');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30007'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30007') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30007') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Winter Puffer Vest', '30008', 'Sleeveless insulated puffer vest', 800.00, 2999.00, 2499.00, 'Columbia', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30008');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30008'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30008') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30008') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Athletic Track Pants', '30009', 'Moisture-wicking training pants', 350.00, 1499.00, 1299.00, 'Nike', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30009');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30009'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30009') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30009') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Formal Cotton Suit', '30010', 'Two-piece classic formal suit', 2500.00, 8999.00, 7999.00, 'Raymond', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30010');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30010'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30010') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30010') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Summer Cargo Shorts', '30011', 'Multi-pocket durable cotton shorts', 250.00, 999.00, 799.00, 'Woodland', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30011');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30011'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30011') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30011') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Thermal Inner Wear', '30012', 'Cozy thermal top and bottom set', 200.00, 799.00, 699.00, 'Lux Cottswool', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30012');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30012'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30012') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30012') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Printed Beach Shirt', '30013', 'Hawaiian floral print short sleeve shirt', 220.00, 899.00, 749.00, 'Jack & Jones', 100, 1, (SELECT id FROM categories WHERE name = 'Men''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30013');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30013'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30013') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30013') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Women's Clothing
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'A-Line Midi Dress', '30014', 'Elegant floral printed midi dress', 500.00, 1999.00, 1699.00, 'Vero Moda', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30014');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30014'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30014') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30014') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Super Skinny Jeans', '30015', 'Stretch denim skinny fit jeans', 650.00, 2499.00, 2199.00, 'Only', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30015');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30015'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30015') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30015') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Anarkali Kurti Set', '30016', 'Traditional cotton anarkali kurti', 800.00, 3499.00, 2999.00, 'BIBA', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30016');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30016'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30016') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30016') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Satin Wrap Blouse', '30017', 'Smooth satin office wear blouse', 300.00, 1299.00, 1099.00, 'Zara', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30017');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30017'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30017') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30017') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Wide Leg Trousers', '30018', 'High-waist formal wide leg trousers', 450.00, 1899.00, 1599.00, 'H&M', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30018');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30018'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30018') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30018') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Oversized Knit Sweater', '30019', 'Cozy loose fit knitted sweater', 500.00, 1999.00, 1799.00, 'Mango', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30019');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30019'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30019') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30019') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Denim Mini Skirt', '30020', 'Classic button-down denim skirt', 250.00, 999.00, 899.00, 'Forever 21', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30020');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30020'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30020') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30020') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Activewear Leggings', '30021', 'High-stretch gym yoga pants', 300.00, 1499.00, 1199.00, 'Adidas', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30021');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30021'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30021') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30021') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Lace Evening Gown', '30022', 'Floor length elegant lace dress', 1800.00, 5999.00, 4999.00, 'AND', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30022');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30022'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30022') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30022') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Casual Linen Shorts', '30023', 'Breathable waist-tie linen shorts', 200.00, 899.00, 749.00, 'Roadster', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30023');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30023'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30023') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30023') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Georgette Party Saree', '30024', 'Designer georgette saree with border', 900.00, 3999.00, 3499.00, 'Sabyasachi', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30024');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30024'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30024') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30024') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Quilted Winter Jacket', '30025', 'Padded winter jacket with hood', 1100.00, 3999.00, 3499.00, 'Columbia', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30025');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30025'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30025') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30025') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Off-Shoulder Crop Top', '30026', 'Trendy summer off-shoulder top', 180.00, 799.00, 649.00, 'Vero Moda', 100, 1, (SELECT id FROM categories WHERE name = 'Women''s Clothing' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30026');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30026'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30026') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30026') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Footwear
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Air Max Sneakers', '30027', 'Comfortable everyday sports sneakers', 2200.00, 6999.00, 5999.00, 'Nike', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30027');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30027'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30027') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30027') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Brogue Leather Shoes', '30028', 'Classic hand-burnished leather brogues', 1800.00, 5499.00, 4799.00, 'Clarks', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30028');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30028'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30028') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30028') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Slip-On Loafers', '30029', 'Suede slip-on driving loafers', 700.00, 2499.00, 1999.00, 'Hush Puppies', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30029');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30029'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30029') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30029') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Stiletto Party Heels', '30030', 'Pointed toe classic high heels', 900.00, 2999.00, 2499.00, 'Steve Madden', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30030');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30030'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30030') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30030') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Running Trail Shoes', '30031', 'Rugged outdoor running shoes', 1300.00, 4499.00, 3799.00, 'Salomon', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30031');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30031'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30031') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30031') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Platform Canvas Shoes', '30032', 'Trendy high-top canvas sneakers', 450.00, 1899.00, 1599.00, 'Converse', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30032');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30032'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30032') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30032') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Chelsea Leather Boots', '30033', 'Sleek elastic-sided ankle boots', 1600.00, 4999.00, 4299.00, 'Woodland', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30033');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30033'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30033') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30033') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Strappy Flat Sandals', '30034', 'Casual summer flat sandals', 250.00, 999.00, 799.00, 'Bata', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30034');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30034'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30034') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30034') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Orthopedic Comfort Slides', '30035', 'Soft footbed orthopedic slides', 300.00, 1299.00, 1099.00, 'Birkenstock', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30035');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30035'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30035') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30035') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Football Cleats', '30036', 'Professional firm ground soccer cleats', 1200.00, 3999.00, 3499.00, 'Adidas', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30036');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30036'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30036') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30036') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Velcro Kids Sneakers', '30037', 'Easy-to-wear sneakers for toddlers', 350.00, 1499.00, 1199.00, 'Puma', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30037');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30037'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30037') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30037') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Wedge Heel Sandals', '30038', 'Fashionable cork sole wedge sandals', 600.00, 2299.00, 1899.00, 'Catwalk', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30038');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30038'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30038') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30038') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Monk Strap Dress Shoes', '30039', 'Double monk strap formal leather shoes', 1500.00, 4499.00, 3999.00, 'Ruosh', 100, 1, (SELECT id FROM categories WHERE name = 'Footwear' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30039');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30039'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30039') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30039') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Home & Kitchen
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Bakeable Ceramic Bowls', '30040', 'Set of 4 oven-safe serving bowls', 350.00, 1199.00, 999.00, 'Borosil', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30040');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30040'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30040') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30040') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Memory Foam Pillow', '30041', 'Orthopedic neck support pillow', 400.00, 1499.00, 1299.00, 'The Sleep Company', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30041');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30041'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30041') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30041') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'French Press Maker', '30042', 'Stainless steel glass coffee plunger', 250.00, 999.00, 799.00, 'InstaCuppa', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30042');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30042'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30042') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30042') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Silicone Spatula Set', '30043', 'Set of 6 heat-resistant kitchen tools', 150.00, 599.00, 499.00, 'Pigeon', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30043');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30043'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30043') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30043') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Thermal Carafe 1.5L', '30044', 'Double wall hot-cold beverage flask', 350.00, 1299.00, 1099.00, 'Milton', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30044');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30044'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30044') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30044') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Microfiber Cleaning Cloths', '30045', '12-pack absorbent polishing rags', 100.00, 399.00, 299.00, 'Scotch-Brite', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30045');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30045'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30045') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30045') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Induction Cooktop', '30046', '2000W touch control induction stove', 1100.00, 3499.00, 2899.00, 'Prestige', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30046');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30046'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30046') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30046') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cotton Bath Mats', '30047', 'Set of 2 soft absorbent floor mats', 120.00, 499.00, 399.00, 'Trident', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30047');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30047'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30047') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30047') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Knife Block 6-Piece', '30048', 'High carbon stainless steel kitchen knives', 600.00, 2299.00, 1999.00, 'Wonderchef', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30048');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30048'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30048') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30048') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Glass Tumbler Set', '30049', 'Pack of 6 premium water/juice glasses', 150.00, 599.00, 449.00, 'Ocean', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30049');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30049'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30049') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30049') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Blackout Window Curtains', '30050', 'Set of 2 thermal insulating drapes', 450.00, 1799.00, 1499.00, 'Cortina', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30050');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30050'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30050') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30050') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Aromatherapy Diffuser', '30051', 'Ultrasonic cool mist humidifier', 300.00, 1199.00, 999.00, 'Allin Exporters', 100, 1, (SELECT id FROM categories WHERE name = 'Home & Kitchen' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30051');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30051'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30051') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30051') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Personal Care
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Sunscreen SPF 50', '30052', 'Broad spectrum matte gel sunscreen', 120.00, 499.00, 449.00, 'La Roche-Posay', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30052');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30052'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30052') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30052') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Electric Toothbrush', '30053', 'Rechargeable sonic power toothbrush', 450.00, 1999.00, 1599.00, 'Oral-B', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1559599189-fe84dea4eb79?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30053');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30053'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30053') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30053') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Tea Tree Face Serum', '30054', 'Clarifying skin serum for blemishes', 180.00, 699.00, 599.00, 'The Body Shop', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30054');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30054'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30054') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30054') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Argan Hair Oil', '30055', 'Nourishing oil for dry damaged hair', 150.00, 599.00, 499.00, 'L''Oreal', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30055');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30055'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30055') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30055') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Dead Sea Mud Mask', '30056', 'Deep pore purifying facial clay mask', 200.00, 799.00, 699.00, 'Mamaearth', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30056');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30056'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30056') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30056') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Cocoa Butter Lip Balm', '30057', 'Hydrating lip balm with vitamin E', 40.00, 149.00, 129.00, 'Nivea', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30057');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30057'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30057') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30057') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Mens Styling Hair Wax', '30058', 'Strong hold matte finish hair wax', 90.00, 299.00, 249.00, 'Gatsby', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30058');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30058'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30058') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30058') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Epsom Bath Salts', '30059', 'Pure natural salts for muscle recovery', 80.00, 349.00, 299.00, 'Dr Teal''s', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1608248597481-496100c8c836?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30059');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30059'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30059') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30059') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Sandalwood Incense Sticks', '30060', 'Premium aromatic hand-rolled agarbatti', 40.00, 199.00, 149.00, 'Cycle Brand', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1607006342411-9243db10e72c?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30060');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30060'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30060') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30060') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Gel Eyeliner Waterproof', '30061', 'Intense black long lasting eyeliner', 120.00, 499.00, 399.00, 'Maybelline', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30061');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30061'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30061') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30061') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Nail Polish Gift Set', '30062', '6 vibrant shades of glossy lacquer', 100.00, 450.00, 349.00, 'Lakme', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30062');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30062'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30062') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30062') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Waterproof Shaving Bag', '30063', 'Compact leather toiletry kit organizer', 150.00, 699.00, 549.00, 'Gillette', 100, 1, (SELECT id FROM categories WHERE name = 'Personal Care' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1626017289578-d017bba91b00?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30063');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30063'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30063') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30063') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Bags & Accessories
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Hard Cabin Suitcase', '30064', 'Lightweight spinner wheels trolley bag', 1400.00, 4999.00, 3999.00, 'American Tourister', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30064');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30064'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30064') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30064') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Bifold Leather Wallet', '30065', 'RFID blocking genuine leather wallet', 250.00, 999.00, 849.00, 'Wildcraft', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553591589-2e5d2a6e04b4?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30065');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30065'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30065') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30065') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Smart Fitness Band', '30066', 'Heart rate and sleep tracking smartband', 600.00, 2499.00, 1999.00, 'Xiaomi', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30066');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30066'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30066') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30066') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Sling Messenger Bag', '30067', 'Waterproof cross-body messenger bag', 300.00, 1299.00, 1099.00, 'Wildcraft', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30067');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30067'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30067') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30067') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Polarized Wayfarer', '30068', 'Classic wayfarer design dark shades', 400.00, 1799.00, 1499.00, 'Ray-Ban', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30068');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30068'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30068') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30068') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Leather Handbag Shoulder', '30069', 'Elegant office shoulder handbag', 800.00, 3299.00, 2799.00, 'Lavie', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30069');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30069'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30069') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30069') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Woolen Muffler Scarf', '30070', 'Soft knitted winter scarf muffler', 120.00, 599.00, 449.00, 'Monte Carlo', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553591589-2e5d2a6e04b4?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30070');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30070'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30070') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30070') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Stainless Steel Thermos', '30071', 'Hot and cold insulated flask 500ml', 180.00, 799.00, 649.00, 'Milton', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30071');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30071'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30071') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30071') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Canvas Gym Duffle', '30072', 'Spacious gym bag with shoe compartment', 350.00, 1499.00, 1199.00, 'Nike', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30072');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30072'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30072') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30072') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Windproof Auto Umbrella', '30073', 'Compact travel umbrella automatic open', 150.00, 599.00, 499.00, 'Citizen', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553591589-2e5d2a6e04b4?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30073');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30073'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30073') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30073') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Womens Clutch Wallet', '30074', 'Fashion evening clutch with card slots', 200.00, 899.00, 749.00, 'Caprese', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30074');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30074'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30074') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30074') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Metal Link Keychain', '30075', 'Heavy duty stainless steel key clip', 40.00, 199.00, 149.00, 'Chumbak', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553591589-2e5d2a6e04b4?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30075');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30075'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30075') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30075') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Leather Card Holder', '30076', 'Slim front pocket card wallet sleeve', 80.00, 399.00, 299.00, 'Wildcraft', 100, 1, (SELECT id FROM categories WHERE name = 'Bags & Accessories' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1553591589-2e5d2a6e04b4?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30076');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30076'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30076') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30076') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Kids & Baby
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Baby Feeding Bottle Set', '30077', 'BPA-free anti-colic feeding bottles', 150.00, 699.00, 599.00, 'Philips Avent', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30077');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30077'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30077') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30077') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Kids Denim dungarees', '30078', 'Soft cotton adjustable straps dungaree', 350.00, 1499.00, 1299.00, 'Max', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30078');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30078'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30078') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30078') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Plush Teddy Bear', '30079', 'Super soft non-toxic cuddly teddy', 120.00, 499.00, 399.00, 'Hamleys', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30079');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30079'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30079') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30079') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Baby Cotton Wipes', '30080', 'Hypoallergenic alcohol-free wet wipes', 60.00, 249.00, 199.00, 'Huggies', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30080');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30080'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30080') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30080') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Board Game Monopoly', '30081', 'Classic property trading board game', 400.00, 1299.00, 1099.00, 'Hasbro', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30081');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30081'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30081') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30081') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Kids Tricycle', '30082', 'Safe training pedal ride-on tricycle', 900.00, 2999.00, 2499.00, 'LuvLap', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30082');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30082'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30082') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30082') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Baby Sleeping Bag', '30083', 'Warm soft velvet wrap sleeping nest', 220.00, 899.00, 749.00, 'Mothercare', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30083');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30083'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30083') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30083') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Lego Building Bricks', '30084', 'Classic creative brick box set', 600.00, 1999.00, 1799.00, 'LEGO', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30084');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30084'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30084') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30084') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Baby Powder 400g', '30085', 'Gentle baby powder clinically proven', 80.00, 249.00, 219.00, 'Johnson''s', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30085');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30085'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30085') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30085') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Kids Sunglasses Elastic', '30086', 'UV protection unbreakable shades', 100.00, 399.00, 299.00, 'Chicos', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30086');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30086'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30086') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30086') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Coloring Book Pack', '30087', 'Set of 5 theme based drawing books', 80.00, 350.00, 299.00, 'Dreamland', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1577401239170-897c3cc71e93?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30087');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30087'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30087') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30087') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Toddler Pyjama Set', '30088', 'Pack of 3 pure cotton nightsuits', 250.00, 999.00, 849.00, 'Miniklub', 100, 1, (SELECT id FROM categories WHERE name = 'Kids & Baby' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30088');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30088'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30088') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30088') AND branch_id = 1);

-- --------------------------------------------------------
-- Category: Stationery & Office
-- --------------------------------------------------------
INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Gel Pens Pack of 20', '30089', 'Smooth writing gel pens assorted colors', 60.00, 299.00, 249.00, 'Uniball', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30089');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30089'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30089') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30089') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Scientific Calculator', '30090', 'Multi-function algebraic calculator', 450.00, 1499.00, 1299.00, 'Casio', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30090');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30090'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30090') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30090') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Leather Journal Planner', '30091', 'Undated refillable notebook binder', 300.00, 1199.00, 999.00, 'Paperkraft', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30091');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30091'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30091') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30091') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Highlighters Pack of 5', '30092', 'Fluorescent chisel tip markers', 40.00, 199.00, 149.00, 'Stabilo Boss', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30092');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30092'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30092') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30092') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Metal Mesh Letter Tray', '30093', '3-tier office document desktop organizer', 200.00, 799.00, 649.00, 'Solo', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30093');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30093'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30093') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30093') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Whiteboard 2x3 Feet', '30094', 'Magnetic dry-erase aluminum frame board', 350.00, 1299.00, 1099.00, 'Pragati Systems', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30094');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30094'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30094') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30094') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Acrylic Paint Set 24', '30095', 'Non-toxic rich pigment acrylic colors', 220.00, 899.00, 749.00, 'Camel', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1577401239170-897c3cc71e93?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30095');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30095'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30095') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30095') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Heavy Duty Stapler', '30096', 'All metal desktop office stapler', 80.00, 399.00, 299.00, 'Kangaro', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30096');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30096'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30096') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30096') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Laminator Machine A4', '30097', 'Quick warm-up office document laminator', 800.00, 2999.00, 2499.00, 'Texet', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30097');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30097'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30097') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30097') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Sticky Notes Cube', '30098', '400 sheets pastel color notes', 30.00, 149.00, 119.00, '3M Post-it', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30098');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30098'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30098') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30098') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Presentation Clicker', '30099', 'Wireless laser pointer slide remote', 250.00, 999.00, 849.00, 'Logitech', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30099');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30099'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30099') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30099') AND branch_id = 1);

INSERT INTO product (id, name, barcode, description, cost_price, mrp, selling_price, brand, stock_quantity, store_id, category_id, created_at, image) SELECT nextval('product_seq'), 'Drafting T-Square Rule', '30100', 'Acrylic transparent marking ruler', 60.00, 299.00, 249.00, 'Omega', 100, 1, (SELECT id FROM categories WHERE name = 'Stationery & Office' AND store_id = 1), NOW(), 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600' WHERE NOT EXISTS (SELECT 1 FROM product WHERE barcode = '30100');
INSERT INTO inventory (branch_id, product_id, quantity, last_updated) SELECT 1, (SELECT id FROM product WHERE barcode = '30100'), 100, NOW() WHERE EXISTS (SELECT 1 FROM product WHERE barcode = '30100') AND NOT EXISTS (SELECT 1 FROM inventory WHERE product_id = (SELECT id FROM product WHERE barcode = '30100') AND branch_id = 1);

