package com.pos.saas.repository;

import com.pos.saas.model.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;

public interface CustomerRepository extends JpaRepository<Customer, Long> {

    // Custom query method generated by Spring Data JPA to search customers
    List<Customer> findByFullNameContainingIgnoreCaseOrEmailContainingIgnoreCase(String fullNameKeyword, String emailKeyword);

    java.util.Optional<Customer> findByEmail(String email);
}