spring.application.name=saas


server.port=5000
spring.datasource.url=jdbc:mysql://localhost:3306/saas-pos
spring.datasource.username=root
spring.datasource.password=mrvarunk#1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Redis (local default)
spring.redis.host=localhost
spring.redis.port=6379
