spring.application.name=saas
server.port=${PORT:5000}

# Dynamic DataSource config: Fallback to local MySQL if environment variables aren't found
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/saas-pos}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mrvarunk#1}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update