spring.application.name=saas
server.port=${PORT:5000}

spring.datasource.url=jdbc:postgresql://ep-misty-credit-ats9jjjv-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gqd7cu0xVJml
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

# Use simple in-memory cache if Redis is not available
spring.cache.type=simple